platform :ios, '13.0'

flutter_root = ENV['FLUTTER_ROOT'] || '/Users/nouraalghamdi/FeelBetterApp/flutter'
raise 'Could not determine FLUTTER_ROOT. Ensure `flutter` is on PATH.' if flutter_root.nil? || flutter_root.empty?

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper.rb'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks! :linkage => :static
  use_modular_headers!
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      flutter_additional_ios_build_settings(target)

      # Keep deployment target consistent
      target.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      # Make sure all pods align on your minimum iOS
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
  end
end
